CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(50) NOT NULL,
	WRITER VARCHAR(20) NOT NULL, -- MEMBER의 MID : 외래키는 상대 테이블의 PK 사용함
	BREAD INT DEFAULT 0,
	BLIKE INT DEFAULT 0,	
	BDATE VARCHAR(25) NOT NULL
);

CREATE TABLE BOARDL(
	BID INT NOT NULL,
	MID VARCHAR(20) NOT NULL,
	CHECKL INT NOT NULL -- 0일때 좋아요+1 / 1일때 좋아요-1
);

SELECT * FROM BOARDL;

SELECT B.*, M.MNAME FROM BOARD B, MEMBER M WHERE B.WRITER = M.MID ORDER BY B.BID DESC;
SELECT B.*, M.MNAME FROM BOARD B, MEMBER M WHERE B.WRITER = M.MID(+) ORDER BY B.BID DESC;